const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      "dist/*",
      ".expo/*",
      "node_modules/*",
      // Generated by scripts/sync-i18n.mjs — never hand-edited, never linted.
      "src/i18n/messages.generated.ts",
    ],
  },
]);
