// AUTO-GENERATED by web-app/scripts/gen-palettes.mjs from
// web-app/src/lib/theme/palettes.ts. DO NOT EDIT — run `npm run sync-palettes`.
//
// `default` is the base [data-theme="light"] .arena look; every other key is one
// of the selectable palettes and matches the slug stored in students.palette.
// ARENA_PALETTE_GROUPS carries the picker's section order; each group label is
// the i18n key `pal.group.<group>`.
import type { ArenaTokens } from "./tokens";

export const ARENA_PALETTE_SLUGS = ["sky","ocean","cyan","aqua","teal","arctic","navy","indigo","violet","lavender","rainbow","aurora","bubblegum","sakura","rose","berry","coral","peach","sunset","amber","sand","lime","mint","emerald","forest","graphite"] as const;

export const ARENA_PALETTE_GROUPS: readonly {
  group: string;
  slugs: readonly string[];
}[] = [
  {
    "group": "bright",
    "slugs": [
      "sky",
      "cyan",
      "rainbow",
      "aurora",
      "bubblegum",
      "rose",
      "coral",
      "sunset",
      "amber"
    ]
  },
  {
    "group": "calm",
    "slugs": [
      "ocean",
      "aqua",
      "mint"
    ]
  },
  {
    "group": "nature",
    "slugs": [
      "teal",
      "lime",
      "emerald",
      "forest"
    ]
  },
  {
    "group": "pastel",
    "slugs": [
      "lavender",
      "sakura",
      "peach"
    ]
  },
  {
    "group": "bold",
    "slugs": [
      "navy",
      "indigo",
      "violet",
      "berry"
    ]
  },
  {
    "group": "neutral",
    "slugs": [
      "arctic",
      "sand",
      "graphite"
    ]
  }
];

export const ARENA_LIGHT_GENERATED: Record<string, ArenaTokens> = {
  "default": {
    "bg": "#fffbf5",
    "bg2": "#fff7ec",
    "panel": "#ffffff",
    "panel2": "#f7f0fe",
    "line": "#e9e0f7",
    "ink": "#2a1a3e",
    "muted": "#6f6486",
    "dim": "#a195bb",
    "lime": "#7c3aed",
    "blue": "#6d28d9",
    "red": "#ff4757",
    "gold": "#ff8a00"
  },
  "sky": {
    "bg": "#f4f9fd",
    "bg2": "#e7f3fb",
    "panel": "#ffffff",
    "panel2": "#eef6fb",
    "line": "#d4e6f2",
    "ink": "#16354b",
    "muted": "#436782",
    "dim": "#517590",
    "lime": "#0d78c5",
    "blue": "#5f23c7",
    "red": "#da1b24",
    "gold": "#a26907"
  },
  "ocean": {
    "bg": "#f4fafd",
    "bg2": "#e7f4fb",
    "panel": "#ffffff",
    "panel2": "#eef7fb",
    "line": "#d0e6f1",
    "ink": "#153647",
    "muted": "#40687d",
    "dim": "#4e768b",
    "lime": "#087bb5",
    "blue": "#087e96",
    "red": "#da1b24",
    "gold": "#9d6b07"
  },
  "cyan": {
    "bg": "#f4fcfd",
    "bg2": "#e7f8fb",
    "panel": "#ffffff",
    "panel2": "#eef9fb",
    "line": "#c8e8ef",
    "ink": "#12383f",
    "muted": "#3d6c76",
    "dim": "#497983",
    "lime": "#047f98",
    "blue": "#1174d7",
    "red": "#da1b24",
    "gold": "#986c06"
  },
  "aqua": {
    "bg": "#f4fdfd",
    "bg2": "#e7fbfa",
    "panel": "#ffffff",
    "panel2": "#eefbfb",
    "line": "#beeceb",
    "ink": "#113938",
    "muted": "#386d6c",
    "dim": "#457a79",
    "lime": "#0b827e",
    "blue": "#147cb1",
    "red": "#da1b24",
    "gold": "#9d6b07"
  },
  "teal": {
    "bg": "#f4fdfc",
    "bg2": "#e7fbf8",
    "panel": "#ffffff",
    "panel2": "#eefbfa",
    "line": "#beece6",
    "ink": "#113934",
    "muted": "#386d66",
    "dim": "#467c75",
    "lime": "#0f8373",
    "blue": "#177ea1",
    "red": "#da1b24",
    "gold": "#a26907"
  },
  "arctic": {
    "bg": "#f6fafb",
    "bg2": "#ebf3f7",
    "panel": "#ffffff",
    "panel2": "#f0f7f9",
    "line": "#d3e6ee",
    "ink": "#193643",
    "muted": "#3f697b",
    "dim": "#4d7789",
    "lime": "#3a7b98",
    "blue": "#4164aa",
    "red": "#da1b24",
    "gold": "#a96507"
  },
  "navy": {
    "bg": "#f4f7fd",
    "bg2": "#e7edfb",
    "panel": "#ffffff",
    "panel2": "#eef2fb",
    "line": "#dbe3f5",
    "ink": "#192c57",
    "muted": "#4c6294",
    "dim": "#5a6fa0",
    "lime": "#2558d0",
    "blue": "#1b78bb",
    "red": "#da1b24",
    "gold": "#9d6b07"
  },
  "indigo": {
    "bg": "#f5f4fd",
    "bg2": "#e8e7fb",
    "panel": "#ffffff",
    "panel2": "#efeefb",
    "line": "#e2e1f6",
    "ink": "#1c1957",
    "muted": "#524e97",
    "dim": "#6b67aa",
    "lime": "#2b22d3",
    "blue": "#6026c5",
    "red": "#da1b24",
    "gold": "#a26907"
  },
  "violet": {
    "bg": "#f8f4fd",
    "bg2": "#f0e7fb",
    "panel": "#ffffff",
    "panel2": "#f4eefb",
    "line": "#eadff6",
    "ink": "#361957",
    "muted": "#704e97",
    "dim": "#8161a6",
    "lime": "#7522d3",
    "blue": "#ad29c2",
    "red": "#da1b24",
    "gold": "#a66707"
  },
  "lavender": {
    "bg": "#f8f6fb",
    "bg2": "#f0ebf7",
    "panel": "#ffffff",
    "panel2": "#f4f0f9",
    "line": "#e8e0f3",
    "ink": "#341f51",
    "muted": "#6d4e97",
    "dim": "#7f62a7",
    "lime": "#7143b1",
    "blue": "#9041aa",
    "red": "#da1b24",
    "gold": "#a66707"
  },
  "rainbow": {
    "bg": "#f7f4fd",
    "bg2": "#ede7fb",
    "panel": "#ffffff",
    "panel2": "#f2eefb",
    "line": "#e6dff6",
    "ink": "#2c1957",
    "muted": "#644e97",
    "dim": "#7864a8",
    "lime": "#561fd6",
    "blue": "#ca2175",
    "red": "#da1b24",
    "gold": "#a66707"
  },
  "aurora": {
    "bg": "#fbf4fd",
    "bg2": "#f6e8fa",
    "panel": "#ffffff",
    "panel2": "#f8eefb",
    "line": "#efddf5",
    "ink": "#481957",
    "muted": "#824c94",
    "dim": "#905ba2",
    "lime": "#a22bca",
    "blue": "#158173",
    "red": "#da1b24",
    "gold": "#a26907"
  },
  "bubblegum": {
    "bg": "#fdf4f9",
    "bg2": "#fbe7f3",
    "panel": "#ffffff",
    "panel2": "#fbeef6",
    "line": "#f5dbea",
    "ink": "#57193d",
    "muted": "#914b73",
    "dim": "#9e5981",
    "lime": "#d32289",
    "blue": "#9026c5",
    "red": "#da1b24",
    "gold": "#b06107"
  },
  "sakura": {
    "bg": "#fcf5f7",
    "bg2": "#f9e9ee",
    "panel": "#ffffff",
    "panel2": "#fbeff3",
    "line": "#f5dde5",
    "ink": "#57192e",
    "muted": "#944c64",
    "dim": "#a05a71",
    "lime": "#c13363",
    "blue": "#b23894",
    "red": "#da1b24",
    "gold": "#ab6407"
  },
  "rose": {
    "bg": "#fdf4f6",
    "bg2": "#fbe7ec",
    "panel": "#ffffff",
    "panel2": "#fbeef1",
    "line": "#f5dde3",
    "ink": "#571929",
    "muted": "#944c5e",
    "dim": "#a05a6b",
    "lime": "#d02550",
    "blue": "#be2d8e",
    "red": "#da1b24",
    "gold": "#ab6407"
  },
  "berry": {
    "bg": "#fdf4f9",
    "bg2": "#fbe7f1",
    "panel": "#ffffff",
    "panel2": "#fbeef5",
    "line": "#f5dde9",
    "ink": "#571938",
    "muted": "#924b6f",
    "dim": "#9e597c",
    "lime": "#ce277a",
    "blue": "#9a2dbe",
    "red": "#da1b24",
    "gold": "#ab6407"
  },
  "coral": {
    "bg": "#fdf6f4",
    "bg2": "#fbebe7",
    "panel": "#ffffff",
    "panel2": "#fbf1ee",
    "line": "#f4dfd9",
    "ink": "#532418",
    "muted": "#8a5447",
    "dim": "#986355",
    "lime": "#d33f1a",
    "blue": "#c2295c",
    "red": "#da1b24",
    "gold": "#a66707"
  },
  "peach": {
    "bg": "#fdf7f4",
    "bg2": "#fbeee7",
    "panel": "#ffffff",
    "panel2": "#fbf3ee",
    "line": "#f3dfd5",
    "ink": "#4d2916",
    "muted": "#835944",
    "dim": "#916752",
    "lime": "#bf541f",
    "blue": "#b93153",
    "red": "#da1b24",
    "gold": "#a26907"
  },
  "sunset": {
    "bg": "#fdf7f4",
    "bg2": "#fbeee7",
    "panel": "#ffffff",
    "panel2": "#fbf3ee",
    "line": "#f2dfd4",
    "ink": "#4b2916",
    "muted": "#825a43",
    "dim": "#906851",
    "lime": "#c5500d",
    "blue": "#d33017",
    "red": "#da1b24",
    "gold": "#a26907"
  },
  "amber": {
    "bg": "#fdfaf4",
    "bg2": "#fbf3e7",
    "panel": "#ffffff",
    "panel2": "#fbf6ee",
    "line": "#f0e1cc",
    "ink": "#433014",
    "muted": "#77603e",
    "dim": "#866e4b",
    "lime": "#a66707",
    "blue": "#c84e10",
    "red": "#da1b24",
    "gold": "#b35d07"
  },
  "sand": {
    "bg": "#fbf9f6",
    "bg2": "#f7f3eb",
    "panel": "#ffffff",
    "panel2": "#f9f6f0",
    "line": "#ede2cf",
    "ink": "#3f3118",
    "muted": "#76613d",
    "dim": "#836e49",
    "lime": "#906f37",
    "blue": "#a46537",
    "red": "#da1b24",
    "gold": "#b06107"
  },
  "lime": {
    "bg": "#fafdf4",
    "bg2": "#f4fbe7",
    "panel": "#ffffff",
    "panel2": "#f7fbee",
    "line": "#d8eab8",
    "ink": "#2a3911",
    "muted": "#596c37",
    "dim": "#657944",
    "lime": "#587f15",
    "blue": "#19853d",
    "red": "#da1b24",
    "gold": "#9d6b07"
  },
  "mint": {
    "bg": "#f4fdfa",
    "bg2": "#e7fbf5",
    "panel": "#ffffff",
    "panel2": "#eefbf7",
    "line": "#beecde",
    "ink": "#11392d",
    "muted": "#396f5f",
    "dim": "#467c6c",
    "lime": "#158463",
    "blue": "#17827e",
    "red": "#da1b24",
    "gold": "#9d6b07"
  },
  "emerald": {
    "bg": "#f4fdf9",
    "bg2": "#e7fbf2",
    "panel": "#ffffff",
    "panel2": "#eefbf5",
    "line": "#c0edd8",
    "ink": "#113b28",
    "muted": "#396f56",
    "dim": "#467c63",
    "lime": "#11864f",
    "blue": "#158173",
    "red": "#da1b24",
    "gold": "#9d6b07"
  },
  "forest": {
    "bg": "#f5fcf7",
    "bg2": "#e9f9ee",
    "panel": "#ffffff",
    "panel2": "#effbf3",
    "line": "#c2edd0",
    "ink": "#113b1f",
    "muted": "#396f4b",
    "dim": "#467c58",
    "lime": "#218542",
    "blue": "#458226",
    "red": "#da1b24",
    "gold": "#986c06"
  },
  "graphite": {
    "bg": "#f8f8fa",
    "bg2": "#eff0f3",
    "panel": "#ffffff",
    "panel2": "#f3f4f6",
    "line": "#e0e3e8",
    "ink": "#2d323c",
    "muted": "#5a6477",
    "dim": "#667187",
    "lime": "#69758c",
    "blue": "#526f98",
    "red": "#da1b24",
    "gold": "#a26907"
  }
};
