// AzeriCard / ABB e-commerce gateway — the MAC ("P_SIGN") SOURCE STRING builder.
//
// THIS FILE IS THE PURE HALF and must stay that way: no `server-only`, no env
// reads, no key material, no Supabase client. It is the same split this repo
// already uses for `lib/planBasket.ts` (pure) vs `lib/auth/subscriptionCore.ts`
// (server-only) — the rule that decides whether money moves has to be unit
// testable without dragging a secret into the test process.
//
// WHY THIS IS THE MOST SECURITY-SENSITIVE FILE IN THE INTEGRATION
// A wrong length prefix or a wrong field order is not a bug that shows up as a
// failed payment; it is an authentication bypass in slow motion. The signature
// is computed over THIS string, so if our string disagrees with theirs the
// verification result stops meaning what we think it means. Every rule below is
// pinned by a known-answer vector in `__tests__/mac.test.ts`, taken verbatim
// from the gateway specification. Do not "simplify" any of it without making
// those vectors pass first.
//
// THE RULES, from the spec (developer.azericard.com, §2.2 / §8.3 / "Callback
// P_SIGN hesablanması"):
//
//   1. Every field value is prefixed with its length in DECIMAL ASCII, and the
//      prefixed values are concatenated in a per-message-type ORDER.
//        AMOUNT "11.48"  ->  "511.48"
//
//   2. If a field is ABSENT, a single "-" is appended in its place and its
//      length is NOT counted. Their words: "Sahə yoxdursa, onun yerinə mesaja
//      '-' simvolu əlavə olunur və P_SIGN hissədə onun uzunluğu nəzərə alınmır."
//      An EMPTY value counts as absent — the callback section says so directly
//      ("əgər ... dəyəri boş göndərilərsə ... '-' işarəsi əlavə edilir").
//
//   3. The MAC never covers the MAC field itself ("P_SIGN").
//
// LENGTH IS MEASURED IN UTF-8 BYTES, not UTF-16 code units. Every field that
// appears in any of the orders below is ASCII by protocol (amounts, currency
// codes, terminal ids, timestamps, hex nonces, numeric orders, RRN/INT_REF,
// and our own MERCH_URL), so the two measures coincide today. Bytes is still
// the correct reading of "ASCII-də onluq sahə uzunluğu" and is what keeps a
// stray non-ASCII character from producing a length we and the gateway would
// count differently.

/** The names the gateway uses on the wire, for the fields a MAC can cover. */
export type MacFieldName =
  | "AMOUNT"
  | "CURRENCY"
  | "TERMINAL"
  | "TRTYPE"
  | "TIMESTAMP"
  | "NONCE"
  | "MERCH_URL"
  | "ORDER"
  | "RRN"
  | "INT_REF"
  | "APPROVAL"
  | "TRAN_TRTYPE";

/** A field bag as it goes on the wire / arrives from the gateway. */
export type MacFields = Partial<Record<MacFieldName, string | null | undefined>>;

// ---------------------------------------------------------------------------
// Field orders, one per message type. These come from the spec's own tables;
// the comment on each names the section so the next reader can re-check it
// against the PDF rather than trusting this file.
// ---------------------------------------------------------------------------

/** §2.2.1 — TRTYPE 0 (pre-authorisation) and TRTYPE 1 (authorisation). */
export const MAC_FIELDS_AUTH = [
  "AMOUNT",
  "CURRENCY",
  "TERMINAL",
  "TRTYPE",
  "TIMESTAMP",
  "NONCE",
  "MERCH_URL",
] as const satisfies readonly MacFieldName[];

/** §2.2.2 — TRTYPE 21 (completion of a pre-authorised sale). */
export const MAC_FIELDS_COMPLETION = [
  "AMOUNT",
  "CURRENCY",
  "TERMINAL",
  "TRTYPE",
  "ORDER",
  "RRN",
  "INT_REF",
] as const satisfies readonly MacFieldName[];

/**
 * §2.2.3 / §2.2.4 — TRTYPE 22 (online reversal) and TRTYPE 24 (offline
 * reversal). The spec prints the same seven fields in the same order for both,
 * and for TRTYPE 21; they are kept as three named constants anyway so a future
 * divergence in one message type cannot silently change the other two.
 */
export const MAC_FIELDS_REVERSAL = [
  "AMOUNT",
  "CURRENCY",
  "TERMINAL",
  "TRTYPE",
  "ORDER",
  "RRN",
  "INT_REF",
] as const satisfies readonly MacFieldName[];

/**
 * §8.3 — TRTYPE 90 (transaction status inquiry).
 *
 * READ THIS BEFORE CHANGING IT. The spec is internally inconsistent here and
 * we resolved the inconsistency deliberately:
 *
 *   * §8.1's REQUEST table lists the fields we must POST as TRAN_TRTYPE, ORDER,
 *     TERMINAL, TRTYPE, TIMESTAMP, NONCE, P_SIGN — and the general MAC rule
 *     says the MAC covers "all fields generated by the merchant system".
 *   * §8.3's WORKED EXAMPLE for exactly this message names five fields —
 *     ORDER, TERMINAL, TRTYPE, TIMESTAMP, NONCE — and prints the resulting
 *     source string with no TRAN_TRTYPE in it.
 *
 * A worked example is evidence about the implementation; a summary sentence is
 * evidence about the documentation. We follow the worked example, and it is
 * pinned as a known-answer vector. `MAC_FIELDS_STATUS_WITH_TRAN_TRTYPE` below
 * is the other reading, kept live and tested, so the owner can switch with one
 * env var (`AZERICARD_STATUS_MAC_INCLUDES_TRAN_TRTYPE=true`) during the live
 * test instead of waiting for a code change. See `config.ts`.
 */
export const MAC_FIELDS_STATUS = [
  "ORDER",
  "TERMINAL",
  "TRTYPE",
  "TIMESTAMP",
  "NONCE",
] as const satisfies readonly MacFieldName[];

/** The alternate TRTYPE 90 reading — see MAC_FIELDS_STATUS. */
export const MAC_FIELDS_STATUS_WITH_TRAN_TRTYPE = [
  "TRAN_TRTYPE",
  "ORDER",
  "TERMINAL",
  "TRTYPE",
  "TIMESTAMP",
  "NONCE",
] as const satisfies readonly MacFieldName[];

/**
 * "Callback P_SIGN hesablanması" — the fields the GATEWAY signs when it posts
 * the result back to our BACKREF.
 *
 * NOTE WHAT IS MISSING: **ORDER IS NOT SIGNED.** A valid signature therefore
 * proves that *some* transaction happened on our terminal for that amount; it
 * proves nothing about WHICH of our orders it belongs to. Anyone who ever
 * obtains one valid callback tuple can replay it against a different ORDER and
 * the signature still verifies. This is why the callback route grants nothing
 * and re-queries the gateway for OUR order (TRTYPE 90) before believing
 * anything. Do not "optimise away" that second call.
 */
export const MAC_FIELDS_CALLBACK = [
  "AMOUNT",
  "TERMINAL",
  "APPROVAL",
  "RRN",
  "INT_REF",
] as const satisfies readonly MacFieldName[];

/** UTF-8 byte length — see the header note on why bytes and not `.length`. */
function byteLength(value: string): number {
  return new TextEncoder().encode(value).length;
}

/**
 * True when the gateway's "field is absent" rule applies: null, undefined, or
 * the empty string. Anything else — including "0" and " " — is present.
 */
export function isAbsent(value: string | null | undefined): boolean {
  return value === null || value === undefined || value === "";
}

/**
 * Build a MAC source string from an ordered list of values.
 *
 * Present value -> `${utf8ByteLength}${value}`.
 * Absent value  -> `-`, with NO length prefix (that is the whole subtlety).
 */
export function buildMacSource(
  values: readonly (string | null | undefined)[],
): string {
  let out = "";
  for (const value of values) {
    if (isAbsent(value)) {
      out += "-";
      continue;
    }
    const v = value as string;
    out += `${byteLength(v)}${v}`;
  }
  return out;
}

/**
 * Build a MAC source string by pulling `order`'s field names out of `fields`.
 * A name that is missing from the bag is "absent" and becomes "-", which is
 * exactly the behaviour the gateway specifies for an omitted field.
 */
export function buildMacSourceFor(
  order: readonly MacFieldName[],
  fields: MacFields,
): string {
  return buildMacSource(order.map((name) => fields[name]));
}

/** MAC source for a TRTYPE 0 / TRTYPE 1 request (§2.2.1). */
export function authMacSource(fields: MacFields): string {
  return buildMacSourceFor(MAC_FIELDS_AUTH, fields);
}

/** MAC source for a TRTYPE 21 completion (§2.2.2). */
export function completionMacSource(fields: MacFields): string {
  return buildMacSourceFor(MAC_FIELDS_COMPLETION, fields);
}

/** MAC source for a TRTYPE 22 / 24 reversal (§2.2.3, §2.2.4). */
export function reversalMacSource(fields: MacFields): string {
  return buildMacSourceFor(MAC_FIELDS_REVERSAL, fields);
}

/**
 * MAC source for a TRTYPE 90 status inquiry (§8.3).
 * `includeTranTrtype` selects the alternate reading documented on
 * MAC_FIELDS_STATUS; the default (false) is the spec's worked example.
 */
export function statusMacSource(
  fields: MacFields,
  includeTranTrtype = false,
): string {
  return buildMacSourceFor(
    includeTranTrtype ? MAC_FIELDS_STATUS_WITH_TRAN_TRTYPE : MAC_FIELDS_STATUS,
    fields,
  );
}

/** MAC source for a callback the gateway posted to our BACKREF. */
export function callbackMacSource(fields: MacFields): string {
  return buildMacSourceFor(MAC_FIELDS_CALLBACK, fields);
}
