// Azerbaijan Cities
// Used for location-based teacher recommendations

export const AZERBAIJAN_CITIES = [
  'Baku',
  'Ganja',
  'Sumqayit',
  'Mingachevir',
  'Lankaran',
  'Shirvan',
  'Nakhchivan',
  'Shaki',
  'Yevlakh',
  'Khankendi',
  'Agdam',
  'Agdash',
  'Agstafa',
  'Agsu',
  'Astara',
  'Balakan',
  'Barda',
  'Beylagan',
  'Bilasuvar',
  'Dashkasan',
  'Fuzuli',
  'Gadabay',
  'Goranboy',
  'Goychay',
  'Goygol',
  'Hajigabul',
  'Imishli',
  'Ismayilli',
  'Jabrayil',
  'Jalilabad',
  'Kalbajar',
  'Kangarli',
  'Khachmaz',
  'Khizi',
  'Khojali',
  'Kurdamir',
  'Lachin',
  'Lerik',
  'Masally',
  'Neftchala',
  'Oghuz',
  'Qabala',
  'Qakh',
  'Qazakh',
  'Qobustan',
  'Quba',
  'Qubadli',
  'Qusar',
  'Saatly',
  'Sabirabad',
  'Salyan',
  'Samukh',
  'Shabran',
  'Shusha',
  'Siazan',
  'Tartar',
  'Tovuz',
  'Ujar',
  'Yardimli',
  'Zangilan',
  'Zaqatala',
  'Zardab',
] as const;

export type AzerbaijanCity = typeof AZERBAIJAN_CITIES[number];

// Major cities (for quick selection)
export const MAJOR_CITIES = [
  'Baku',
  'Ganja',
  'Sumqayit',
  'Mingachevir',
  'Lankaran',
  'Shirvan',
  'Nakhchivan',
  'Shaki',
] as const;
