// Sync the trilingual UI catalog FROM the web app (the single source of truth)
// into src/i18n/messages.generated.ts. This script is the ONLY way web keys
// enter the mobile app — never hand-edit the generated file. Mobile-only
// strings live in src/i18n/messages.mobile.ts (merged at runtime).
//
// Usage: npm run sync-i18n   (from mobile-app/)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
const webMessagesPath = join(here, "..", "..", "web-app", "src", "i18n", "messages.ts");
const outPath = join(here, "..", "src", "i18n", "messages.generated.ts");

const source = readFileSync(webMessagesPath, "utf8");

// Isolate the object literal assigned to `export const messages`.
const startMarker = source.indexOf("export const messages");
if (startMarker === -1) {
  console.error("sync-i18n: could not find `export const messages` in the web catalog");
  process.exit(1);
}
const braceStart = source.indexOf("{", startMarker);
// Walk to the matching closing brace (string-aware so braces inside values
// cannot derail the scan).
let depth = 0;
let end = -1;
let inString = null;
for (let i = braceStart; i < source.length; i++) {
  const ch = source[i];
  const prev = source[i - 1];
  if (inString) {
    if (ch === inString && prev !== "\\") inString = null;
    continue;
  }
  if (ch === '"' || ch === "'" || ch === "`") {
    inString = ch;
    continue;
  }
  if (ch === "/" && source[i + 1] === "/") {
    i = source.indexOf("\n", i);
    if (i === -1) break;
    continue;
  }
  if (ch === "{") depth++;
  if (ch === "}") {
    depth--;
    if (depth === 0) {
      end = i;
      break;
    }
  }
}
if (end === -1) {
  console.error("sync-i18n: could not find the end of the messages object");
  process.exit(1);
}
const literal = source.slice(braceStart, end + 1);

// Evaluate in an empty sandbox — the catalog is plain string literals.
let messages;
try {
  messages = vm.runInNewContext(`(${literal})`, Object.create(null), {
    timeout: 5000,
  });
} catch (err) {
  console.error("sync-i18n: failed to evaluate the web catalog:", err.message);
  process.exit(1);
}

const locales = ["az", "en", "ru"];
for (const l of locales) {
  if (!messages[l] || typeof messages[l] !== "object") {
    console.error(`sync-i18n: locale '${l}' missing from the web catalog`);
    process.exit(1);
  }
}
const counts = locales.map((l) => `${l}=${Object.keys(messages[l]).length}`).join(" ");

const banner = `// AUTO-GENERATED by scripts/sync-i18n.mjs from web-app/src/i18n/messages.ts.
// DO NOT EDIT — run \`npm run sync-i18n\` to refresh. Mobile-only strings go in
// messages.mobile.ts instead.
export type Locale = "az" | "en" | "ru";

export const messages: Record<Locale, Record<string, string>> = `;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + JSON.stringify(messages, null, 2) + ";\n", "utf8");
console.log(`sync-i18n: wrote ${outPath} (${counts})`);
